// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: municipio.sql

package database

import (
	"context"
)

const getMunicipio = `-- name: GetMunicipio :one
SELECT id, id_provincia, name FROM "municipio" WHERE id =$1
`

func (q *Queries) GetMunicipio(ctx context.Context, id int64) (Municipio, error) {
	row := q.db.QueryRowContext(ctx, getMunicipio, id)
	var i Municipio
	err := row.Scan(&i.ID, &i.IDProvincia, &i.Name)
	return i, err
}
