// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: provincia.sql

package database

import (
	"context"
)

const getProvincia = `-- name: GetProvincia :one
SELECT id, name FROM "provincia" WHERE id =$1
`

func (q *Queries) GetProvincia(ctx context.Context, id int64) (Provincium, error) {
	row := q.db.QueryRowContext(ctx, getProvincia, id)
	var i Provincium
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
